local remap = vim.api.nvim_set_keymap

remap('n','<Esc>',':noh<cr>', {noremap = true})
remap('n','<Leader><tab>',':bnext<cr>', {noremap = true})
remap('n','<Leader><S-tab>',':bprevious<cr>', {noremap = true})
remap('n','<Leader>gs',':G<cr>', {noremap = true})
remap('x','<Leader>p','"_dP', {})
remap('n','<Leader>u',':UndotreeToggle<cr>', {})
remap('n','<Leader>e','<Cmd>CocCommand explorer<CR>', {noremap = true})
remap('n','<Leader>w','<c-w>', {noremap = true})
remap('n','ga','<Plug>(EasyAlign)', {noremap = false})
remap('x','ga','<Plug>(EasyAlign)', {noremap = false})
remap('n','<c-j>','<c-w><c-j>', {noremap = true})
remap('n','<c-k>','<c-w><c-k>', {noremap = true})
remap('n','<c-h>','<c-w><c-h>', {noremap = true})
remap('n','<c-l>','<c-w><c-l>', {noremap = true})
remap('n',';;',':%s:::g<Left><Left><Left>', {noremap = true})
remap('n',';\'',':%s:::gc<Left><Left><Left><Left>', {noremap = true})
remap('n',';,',':%s:::gci<Left><Left><Left><Left><Left>', {noremap = true})
remap('n',']h','<Plug>(GitGutterNextHunk)', {noremap = true})
remap('n','[h','<Plug>(GitGutterPrevHunk)', {noremap = true})
vim.keymap.set('n', '<F5>', function() require('dap').continue() end)
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end)
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end)
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end)
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>B', function() require('dap').set_breakpoint() end)
vim.keymap.set('n', '<Leader>lp', function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end)
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end)
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end)
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end)
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end)
vim.keymap.set('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end)
vim.keymap.set('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end)
