general.import = ["/home/cristian/.config/alacritty/themes/themes/everforest_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font Mono"

[font.bold_italic]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "Full"

# [[keyboard.bindings]]
# key = "H"
# mods = "Control|Shift"
# chars = "htop\x0D"

# [keyboard]
# bindings = [
#   { key = "T", mods = "Control|Shift", command = "/home/cristian/.local/bin/start-cei-tmux-session" }
# ]
[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", command = { program = "sh", args = ["-c", "/home/cristian/.local/bin/start-cei-tmux-session"] } }
]

