general.import = ["/home/cristian/.config/alacritty/themes/themes/nord.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font Mono"

[font.bold_italic]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "None"

[colors]
# primary = { background = "0x000000", foreground = "0xd0d0d0" }
# transparent_background_colors = true

[terminal]
